[package]
name = "day23"
version = "0.1.0"
authors = ["Rob Pilling <robpilling@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[profile.release]
overflow-checks = true # won't get fooled again
