#!/usr/bin/perl

require '../lib';

sub fuel_for_mass {
	my $mass = shift();

	my $fuel = int($mass / 3) - 2;
	#print "$mass -> $fuel\n";

	if($fuel <= 0){
		return 0;
	}

	my $next = fuel_for_mass($fuel);
	return $fuel + $next;
}

sub assert {
	if(!shift()){
		print "failed\n";
	}
}

sub egtest1 {
	assert(fuel_for_mass(12) == 2);
	assert(fuel_for_mass(14) == 2);
	assert(fuel_for_mass(1969) == 654);
	assert(fuel_for_mass(100756) == 33583);
}

sub egtest2 {
	assert(fuel_for_mass(14) == 2);
	assert(fuel_for_mass(1969) == 966); # At first, a module of mass 1969 requires 654 fuel. Then, this fuel requires 216 more fuel (654 / 3 - 2). 216 then requires 70 more fuel, which requires 21 fuel, which requires 5 fuel, which requires no further fuel. So, the total fuel required for a module of mass 1969 is 654 + 216 + 70 + 21 + 5 = 966.
	assert(fuel_for_mass(100756) == 50346); # The fuel required by a module of mass 100756 and its fuel is: 33583 + 11192 + 3728 + 1240 + 411 + 135 + 43 + 12 + 2 = 50346.
}


egtest2();

my @fuels =
	map { fuel_for_mass($_) }
	map { chomp; $_ }
	contents('./input');

my $t = 0;
$t += $_ for @fuels;

print "$t\n";

# Fuel required to launch a given module is based on its mass. Specifically, to find the fuel required for a module, take its mass, divide by three, round down, and subtract 2.
#
# For example:
#
#     For a mass of 12, divide by 3 and round down to get 4, then subtract 2 to get 2.
#     For a mass of 14, dividing by 3 and rounding down still yields 4, so the fuel required is also 2.
#     For a mass of 1969, the fuel required is 654.
#     For a mass of 100756, the fuel required is 33583.
#
# The Fuel Counter-Upper needs to know the total fuel requirement. To find it, individually calculate the fuel needed for the mass of each module (your puzzle input), then add together all the fuel values.
#
# What is the sum of the fuel requirements for all of the modules on your spacecraft?
