[package]
name = "intcode"
version = "0.1.0"
authors = ["Rob Pilling <robpilling@gmail.com>"]
edition = "2018"

[dependencies]

[lib]
name = "intcode"
path = "src/lib.rs"

[[bin]]
name = "day7"
path = "src/day7.rs"
